services:
  qurrium-docs-sphinx:
    working_dir: /app
    volumes:
      - ./build:/build
      - ./sphinx-build:/sphinx-build
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        git fetch
        git pull
        echo "======================================================================"
        echo "### Building Sphinx documentation for Qurrium"
        echo "======================================================================"
        echo "| Building docs for version: ${QURRIUM_VERSION}"
        echo "| Actual Qurrium version: $(cat /.venv/lib/python3.13/site-packages/qurry/VERSION.txt)"
        echo "| Documentation version by branch or tag: ${DOC_VERSION}"
        echo "| git-hash: $(git log -n1 --format=%h --abbrev=7)"
        echo "----------------------------------------------------------------------"
        . /.venv/bin/activate
        mkdir -p "/sphinx-build/${QURRIUM_VERSION}"
        sphinx-build -b html "/app/docs" "/sphinx-build/${QURRIUM_VERSION}"
        echo "----------------------------------------------------------------------"
        echo "| Clear existing build at mount point: /build/${QURRIUM_VERSION}"
        rm -rf /build/${QURRIUM_VERSION}
        echo "| Copying built result to mount point: /build/${QURRIUM_VERSION}"
        mv "/sphinx-build/${QURRIUM_VERSION}" "/build/${QURRIUM_VERSION}"

    build:
      args:
        QURRIUM_VERSION: ${QURRIUM_VERSION}
        DOC_VERSION: ${DOC_VERSION}
      context: .
      dockerfile: Dockerfile
