services:
  qurrium-docs-sphinx:
    working_dir: /build
    volumes:
      - ./build:/build
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sphinx-build -b html "/tmp/docs" "/build/html/${QURRIUM_VERSION}"
    build:
      args:
        QURRIUM_VERSION: ${QURRIUM_VERSION}
      context: .
      dockerfile: Dockerfile
