services:
  qurrium-docs-sphinx:
    volumes:
      - ./docs:/docs # Mount current directory as /docs inside container
    working_dir: /docs
    command: make html
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
