name: Test Unit
author: Harui (Huai-Chun Chang)
description: "The basic unit to test documentations of Qurry"

runs:
  using: "composite"
  steps:
    - name: Check OS
      run: |
        echo "======================================================================"
        echo "### Test Documentation ..............................................."
        echo "======================================================================"
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "| This action is not yet proved to work on Windows"
        else
          echo "| This action is proved to work on UNIX-like $RUNNER_OS"
        fi
      shell: bash

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pipe pip
        python -c "print('### Dependencies are ready to go '.ljust(70, '.'))"
        python -m pip install -r requirements.txt --upgrade
        python -m pip install -r requirements-test.txt --upgrade
        python -m pip install qurrium --upgrade
        python -c "print('### Dependencies are ready to go '.ljust(70, '.'))"

    - name: Lint with flake8
      shell: bash
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 . --count --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python -m flake8 . --count --exit-zero --statistics

    - name: List Pip
      shell: bash
      run: |
        python -c "import qurry; print(qurry.__version__)"
        python -m pip list

    - name: Test with pytest
      shell: bash
      run: |
        python -m pytest --nbmake "./docs"
