name: Deploy Jupyter Book

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_book_and_deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up Git user
        run: |
          git config --local user.name ${{ github.repository_owner }}_action_bot
          git config --local user.email ${{ github.repository_owner }}@users.noreply.github.com

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-test.txt
          python -m pip install -r requirements-book.txt

      - name: Format Python files
        run: |
          black .

      - name: Build the book
        run: |
          jupyter-book build --all docs

      - name: Create Tag and Push
        run: |
          python versioning.py

      - name: Deploy
        run: |
          python ghp_setup.py
