# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test_py_latest_and_oldest:
    if: ${{ !startsWith(github.event.pull_request.title, 'skip-test:') }}
    name: Test on Python Latest and Oldest
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.13"]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Test Unit
        uses: ./.github/actions/test-unit

  test_build:
    if: ${{ !startsWith(github.event.pull_request.title, 'skip-test:') }}
    name: Test Build
    runs-on: self-hosted
    needs:
      - test_py_latest_and_oldest
    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-test.txt
          python -m pip install -r requirements-book.txt

      - name: Build the book
        run: |
          jupyter-book build --all docs
